openapi: 3.0.0
info:
  title: anki-kun API
  version: "1.0"
paths:
  /login:
    post:
      summary: ログイン処理
      description: IDとパスワードをサーバーに渡し、ログインの可否を問う
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                password:
                  type: string
      responses:
        '200':    # status code
          description: ログイン成功
          content:
            application/json:
              schema:
                type: string
        '401':
          description: ログイン失敗
          content:
            application/json:
              schema:
                type: string
        '500':
          description: サーバー処理失敗
          content:
            application/json:
              schema:
                type: string
  /signin:
    post:
      summary: 新規会員登録
      description: IDとパスワードを渡し、新規会員登録の結果を問う。
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                password:
                  type: string
      responses:
        '200':    # status code
          description: 新規会員登録成功
          content:
            application/json:
              schema:
                type: string
        '400':
          description: 新規会員登録失敗
          content:
            application/json:
              schema:
                type: string
        '500':
          description: サーバー処理失敗
          content:
            application/json:
              schema:
                type: string
  /list/{listId}:
    get:
      summary: 単語リスト一覧を取得
      description: ホームページアクセス時、単語リストを表示
      parameters:
        - in: path
          name: listId
          schema:
            type: string
          required: true
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  listArray:
                    items:
                      type: object
                    example:
                      - { wordId, wordTitle }
                      - { wordId, wordTitle }
                      - { wordId, wordTitle }
  /list/{listId}/word/{wordId}:
    get:
      summary: 単語詳細取得
      description: 単語の詳細情報をlistIdとwordIdから取得
      parameters:
        - in: path
          name: listId
          schema:
            type: string
          required: true
        - in: path
          name: wordId
          schema:
            type: string
          required: true
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  wordId:
                    type: integer
                  englishWord:
                    type: string
                  japaneseWord:
                    type: string
                  audioKey:
                    type: string